;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack.motion1",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack.motion2",DevComment="")
+GameplayTagList=(Tag="Chara.Phase.Fight",DevComment="")
+GameplayTagList=(Tag="Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Battle.AutoAttack",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Hit",DevComment="")

