;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Battle.Art",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack.motion1",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Battle.AutoAttack.motion2",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Move",DevComment="")
+GameplayTagList=(Tag="Ability.Recast",DevComment="")
+GameplayTagList=(Tag="Ability.Recast.art1",DevComment="")
+GameplayTagList=(Tag="Ability.Recast.Art2",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.Art1",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.Art2",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.Art3",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.Art4",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.NoRecast",DevComment="")
+GameplayTagList=(Tag="Art.Cooldown.Talent",DevComment="")
+GameplayTagList=(Tag="Chara.Phase.Fight",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Talent",DevComment="")
+GameplayTagList=(Tag="Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Effect.Damage.ArtBonus",DevComment="")
+GameplayTagList=(Tag="Event.Battle.AutoAttack",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Hit",DevComment="")

